### ISSUE TITLE
about the train net question

### ISSUE THREAD

**Issue by duanLH** [ShuangLI59/person_search#6]
Q1.
In the roi-data layer, the {param_str: "'num_classes': 2\n'bg_aux_label': 5532"}, 
but in the /lib/roi_data_layer/layer.py, I'm not find the reference about the bg_aux_label. I want to know where use the param bg_aux_label.
Q2.
compared with faster rcnn code, the 
layer {
  name: "silence"
  type: "Silence"
  bottom: "labels"
}
is Added, so I want to know the function of this layer in the person_search project

thanks for your explanation

**Comment by Cysu** [comment]
1. The `bg_aux_label` is used [here](https://github.com/ShuangLI59/person_search/blob/52350f294541ceee9cb5b3c04ab728a7babf0bed/lib/rpn/proposal_target_layer.py#L162) that indicates the proposal is not a person.

2. Silence layer is to mute the blob output. We use as target the `pid_labels` rather than the `labels` in our classification branch.

**Comment by duanLH** [comment]
OK ~ get the knowledge again
